### ISSUE TITLE
Frontend TODO list

### ISSUE THREAD

**Issue by altheaden** [franklindyer/agora-app#69]
- [x] Friends - friend request button; friend requests list; delete friends
- [x] Password recovery
- [x] Bug reporting page / contact us page
- [x] Account settings confirmation page (some page with a secondary confirmation before attempting to change email/password)
- [x] Liking and disliking posts buttons
- [x] Image uploading, linking, and viewing
- [x] Change profile pictures

----------------------------------------------------------------------------------------

Cosmetic / low importance:
- [ ] Password verification check ("confirm your password" field)
- [ ] Post and comment writing boxes that dynamically resize based on content

@franklindyer Please feel free to add a comment to this issue if you notice any additional TODO items that aren't listed here, and I'll add them.
